// <auto-generated />
using System;
using DHS.MoviesApp.Repository.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DHS.MoviesApp.Repository.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200402171525_SeedingMoviesData")]
    partial class SeedingMoviesData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DHS.MoviesApp.Domain.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discription");

                    b.Property<string>("Image");

                    b.Property<string>("ImageName");

                    b.Property<string>("ImageType");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new { Id = new Guid("11223344-5566-7788-99aa-bbccddeeff00"), Name = "Movie 1" },
                        new { Id = new Guid("12223344-2566-7788-99aa-bbccddeeff00"), Name = "Movie 2" },
                        new { Id = new Guid("13223344-3566-7788-99aa-bbccddeeff00"), Name = "Movie 3" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
